# Generated by Django 4.2.15 on 2024-09-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.SmallIntegerField()),
                ('tags', models.SmallIntegerField()),
                ('image', models.ImageField(height_field=160, upload_to='player_images/', width_field=160)),
            ],
        ),
    ]
